### ISSUE TITLE
questions about arrow-private building commands

### ISSUE THREAD

**Issue by AveryQi115** [XinyuZeng/EvaluationOfColumnarFormats#1]
Hi, wondering what commands you are using for arrow-private build.

I saw there are multiple customized presets as `openformat-release`, `openformat-release-static` and etc. However, I'm trying to build it on Ubuntu20.04 with the exact same settings as the paper has described and simple build commands as `mkdir build && cd build; cmake .. --preset openformat-release; cmake --build .; make install`, the builds failed as it cannot find some libraries. Manually setting the options for the libraries won't work either.

I'm wondering is there any other options you're using while building arrow-private? I appreciate your help and thanks a lot!

**Comment by XinyuZeng** [comment]
`openformat-release` is the option for building the arrow repo. What's the error message? If it is an error from an Arrow dependency lib, you can try [bundled build](https://arrow.apache.org/docs/developers/cpp/building.html#individual-dependency-resolution) for that dependency instead of system build to see if it can solve the issue.

**Comment by AveryQi115** [comment]
It shows `libprotoc was set to Protobuf_PROTOC_LIBRARY-NOTFOUND` no matter I'm using `-DARROW_DEPENDENCY_SOURCE=BUNDLED` or apt install protobuf-compiler without the arguments. I trie to build under normal release mode and manually set protoc_root but it failed in `make install` later saying cannot find the package.

Besides, I have a question regarding the location of executable files. I'm quite curious why it is located in `arrow-private/cpp/out/build/openformat-release/release/parquet-scan-columnbatch`? My command won't generate a openformat-release dir automatically.

**Comment by XinyuZeng** [comment]
Could you try 
```bash
cmake --preset openformat-release -B./out/build/openformat-release -G Ninja
cmake --build ./out/build/openformat-release --parallel 8 --target parquet-scan-columnbatch
```
ninja is optional (it is just recommended by Arrow), make should also be ok.

Sorry for the confusion, I will include the build commands in the repo.

**Comment by AveryQi115** [comment]
icic. Thank you! and I assume that it is might related to my conda settings as it is built within an activated conda environment.

**Comment by AveryQi115** [comment]
I found out that building shared libraries together with system builds might have caused too many linker errors and version mismatch.

I build the file finally using this command:
```
cmake --preset openformat-release-static -B./out/build/openformat-release-static -G Ninja -DARROW_DEPENDENCY_SOURCE=BUNDLED -DARROW_DEPENDENCY_USE_SHARED=OFF -DARROW_BUILD_SHARED=OFF
cmake --build ./out/build/openformat-release --parallel 8 --target parquet-scan-columnbatch
```
